# Generated by Django 3.2 on 2024-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(verbose_name='金額')),
                ('content', models.TextField(verbose_name='メモ')),
                ('duedate', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
