# Generated by Django 3.2 on 2024-01-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='title2',
            field=models.IntegerField(null=True, verbose_name='収入'),
        ),
        migrations.AlterField(
            model_name='money',
            name='content',
            field=models.TextField(null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.IntegerField(null=True, verbose_name='支出'),
        ),
    ]
