# Generated by Django 3.2 on 2024-01-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240113_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='balance',
            field=models.IntegerField(null=True, verbose_name='残高'),
        ),
    ]
