# Generated by Django 3.2 on 2024-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_money_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='title2',
            field=models.IntegerField(null=True),
        ),
    ]
