# Generated by Django 3.2 on 2024-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_money_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.IntegerField(null=True),
        ),
    ]
