# Generated by Django 3.2 on 2024-01-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240113_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='balance',
        ),
    ]
