# Generated by Django 3.2 on 2024-01-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_money_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(max_length=255, verbose_name='メール')),
                ('yen', models.IntegerField(null=True)),
            ],
        ),
    ]
