# Generated by Django 3.2 on 2024-01-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_want'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='memo',
            field=models.TextField(max_length=255),
        ),
    ]
