# Generated by Django 3.2 on 2024-01-18 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_want_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
