# Generated by Django 3.2 on 2024-01-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_money_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='content',
            field=models.TextField(null=True, verbose_name='メモ'),
        ),
    ]
