# Generated by Django 3.2 on 2024-01-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_money_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.IntegerField(null=True, verbose_name='支出'),
        ),
        migrations.AlterField(
            model_name='money',
            name='title2',
            field=models.IntegerField(null=True, verbose_name='収入'),
        ),
    ]
