# Generated by Django 3.2 on 2024-01-18 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240118_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
