# Generated by Django 3.2 on 2024-01-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240118_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
