# Generated by Django 3.2 on 2024-01-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_money_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
