# Generated by Django 3.2 on 2024-01-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_money_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.IntegerField(default=1, verbose_name='支出'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money',
            name='title2',
            field=models.IntegerField(default=7, verbose_name='収入'),
            preserve_default=False,
        ),
    ]
