# Generated by Django 3.2 on 2024-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20240118_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.IntegerField(null=True, verbose_name='支出'),
        ),
        migrations.AlterField(
            model_name='money',
            name='title2',
            field=models.IntegerField(null=True, verbose_name='収入'),
        ),
    ]
