# Generated by Django 3.2 on 2024-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20240119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='content',
            field=models.TextField(null=True, verbose_name='メモ'),
        ),
    ]
