# Generated by Django 3.2 on 2024-01-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_money_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
