# Generated by Django 3.2 on 2024-01-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_money_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.IntegerField(default=0, null=True, verbose_name='支出'),
        ),
        migrations.AlterField(
            model_name='money',
            name='title2',
            field=models.IntegerField(default=0, null=True, verbose_name='収入'),
        ),
    ]
