# Generated by Django 3.2 on 2024-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20240120_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='memo',
            field=models.TextField(max_length=255, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='want',
            name='yen',
            field=models.IntegerField(null=True, verbose_name='金額'),
        ),
    ]
